### ISSUE TITLE
Enabling Checking

### ISSUE THREAD

**Issue by pquerner** [llagerlof/MyLogPHP#5] opened 2018-01-04 08:38 UTC
Currently it is checked if logging is enabled every time something is logged. This should be saved to a class property, so it saves time and memory.

**Comment by pmanolak** [comment] 2021-01-21 21:51
@llagerlof  do we have any further update about this change?

**Comment by llagerlof** [comment] 2021-01-23 01:17
> @llagerlof do we have any further update about this change?

Since this is an improvement, not a bug fix, it wasn't my top priority. But is an easy change. I will do it in the next days.

**Comment by pmanolak** [comment] 2021-02-03 21:50
Much appreciate for your response!

Regards,
Panagiotis.

**Comment by llagerlof** [comment] 2021-04-01 15:57
Fixed in f0748111dd78c7d0059b0273c72e7dbf1d404548

**Closed as completed by llagerlof** 2021-04-01 15:57 UTC
Labels: enhancement

**Comment by pmanolak** [comment] 2021-04-01 21:49
Thanks a lot for your work!
